/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/magic-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a magic-link email
         * @description Always returns 202 with an identical body whether or not the email is
         *     registered (no account enumeration). Rate-limited per email and per IP.
         *     The email contains a link that opens the app with a single-use token
         *     (15-min expiry).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                    };
                };
            };
            responses: {
                /** @description Accepted (regardless of whether the email is registered). */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                429: components["responses"]["TooManyRequests"];
                default: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/magic-link/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a magic-link token for a session
         * @description Consumes the single-use token from the email deep link. Creates the
         *     account on first sign-in. Signing in during a pending account deletion
         *     cancels the deletion (ADR-0004).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Opaque token from the magic-link URL. */
                        token: string;
                    };
                };
            };
            responses: {
                /** @description Session created. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenPair"];
                    };
                };
                /** @description Token invalid, expired, or already consumed. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
                default: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oidc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in with a Google or Apple id token
         * @description The app performs native sign-in and sends the provider id token; the
         *     backend verifies signature/issuer/audience/nonce and finds-or-creates
         *     the user keyed on (provider, subject), linking by verified email.
         *     Signing in during a pending account deletion cancels the deletion.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        provider: "google" | "apple";
                        idToken: string;
                        /** @description Raw nonce used in the native sign-in request, when the platform requires it. */
                        nonce?: string;
                        /** @description Apple only exposes the user's name to the app on first authorization and it is absent from the id token — the app passes it here on first sign-in. Can be absent even then; the backend derives a placeholder from the email local-part and the user sets their name in onboarding (PATCH /me). */
                        name?: string;
                    };
                };
            };
            responses: {
                /** @description Session created (account created on first sign-in). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenPair"];
                    };
                };
                /** @description Id token failed verification. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
                default: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate a refresh token
         * @description Exchanges a valid refresh token for a new token pair. The old refresh
         *     token is revoked (single-use rotation). Reuse of a rotated token
         *     revokes the whole token family and returns 401.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refreshToken: string;
                    };
                };
            };
            responses: {
                /** @description New token pair. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenPair"];
                    };
                };
                /** @description Refresh token invalid, expired, revoked, or reused. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
                default: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sign-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out (revoke a refresh token)
         * @description Revokes the given refresh token. Always 204, even if already revoked.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refreshToken: string;
                    };
                };
            };
            responses: {
                /** @description Revoked (idempotent). */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                default: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current user's profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Profile. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                default: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update profile (name, units)
         * @description "Changes apply everywhere, right away" — units affect display only; stored values stay metric.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        units?: components["schemas"]["Units"];
                    };
                };
            };
            responses: {
                /** @description Updated profile. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                default: components["responses"]["Problem"];
            };
        };
        trace?: never;
    };
    "/me/vacations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the stored vacation ranges
         * @description The ranges as last written; an empty array if the user has never set any.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Vacation ranges. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VacationRange"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                default: components["responses"]["Problem"];
            };
        };
        /**
         * Replace the stored vacation ranges
         * @description Replace-on-write: the whole array is re-encrypted and replaces the previous value. No merge, no server-side interpretation. Echoes what was stored.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VacationRange"][];
                };
            };
            responses: {
                /** @description The stored vacation ranges. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VacationRange"][];
                    };
                };
                400: components["responses"]["Problem"];
                401: components["responses"]["Unauthorized"];
                default: components["responses"]["Problem"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Request account deletion (7-day grace)
         * @description Starts the 7-day grace period (ADR-0004): account marked pending
         *     deletion, all refresh tokens revoked. Any successful sign-in during the
         *     window cancels the deletion. After 7 days: crypto-shred + hard delete.
         *     Idempotent — repeating the request does not move the date.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deletion scheduled. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: date-time */
                            deletionEffectiveAt: string;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                default: components["responses"]["Problem"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List entries (timeline)
         * @description Flat list ordered by occurredAt descending, cursor-paginated. Pass
         *     `date` for a single day (the Today screen); omit it and follow
         *     `nextCursor` for infinite scroll into the past. The app groups by day
         *     client-side (app review pt 2). No `?updatedSince=` delta sync in v0 —
         *     the app refreshes by day and infers deletes from omissions (app
         *     review pt 3; revisit with tombstones only if multi-device happens).
         *
         *     0.4.0 (BE-017) adds two additive filters, both composable with `cursor`
         *     and `limit`:
         *       - `from`/`to` — an explicit half-open `[from, to)` occurredAt window
         *         (either bound optional) for trends/history bulk reads. Mutually
         *         exclusive with `date` (sending both is a 400).
         *       - `type` — a CSV allow-list of entry types. Home sends
         *         `type=meal,water,workout` (excludes check-ins); Habits sends
         *         `type=checkin`. `checkin` is accepted now and returns nothing until
         *         that entry type ships (BE-024).
         */
        get: {
            parameters: {
                query?: {
                    /** @description Local calendar day to fetch, interpreted with `tz`. Not combinable with from/to. */
                    date?: string;
                    /** @description IANA timezone used to resolve `date` to a time range (e.g. Europe/Lisbon). Required when `date` is present. */
                    tz?: string;
                    /** @description Inclusive lower bound (occurredAt >=). Not combinable with `date`. */
                    from?: string;
                    /** @description Exclusive upper bound (occurredAt <). Not combinable with `date`. */
                    to?: string;
                    /** @description CSV allow-list of entry types to include. `checkin` is accepted forward-compatibly (BE-024) and matches nothing until then. */
                    type?: ("meal" | "water" | "workout" | "checkin")[];
                    /** @description Opaque cursor from a previous response. */
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Page of entries. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["LogEntry"][];
                            /** @description Absent when there are no older entries. */
                            nextCursor?: string;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                default: components["responses"]["Problem"];
            };
        };
        put?: never;
        /**
         * Create a log entry (user-confirmed)
         * @description The single write path to the log — AI drafts reach it only after the
         *     user confirms. Requires an Idempotency-Key: retrying the same key
         *     returns the original entry (200) instead of duplicating; the same key
         *     with a different body returns 409.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Client-generated key, unique per logical create, reused on retries. Usually a UUID; for naturally-idempotent domains it is deterministic — check-ins use `habitId:date` so a habit can be checked in once per day (BE-024). */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NewEntry"];
                };
            };
            responses: {
                /** @description Idempotent replay — the entry previously created with this key. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LogEntry"];
                    };
                };
                /** @description Created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LogEntry"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Idempotency-Key was already used with a different request body. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
                default: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entryId: string;
            };
            cookie?: never;
        };
        /** Get one entry (meal/workout detail screens) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entryId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The entry. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LogEntry"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                default: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete an entry
         * @description Hard delete — the log belongs to the user.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entryId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted (idempotent — deleting a missing entry also returns 204). */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                default: components["responses"]["Problem"];
            };
        };
        options?: never;
        head?: never;
        /**
         * Update an entry
         * @description Partial update. `type` is immutable; sending a `detail` replaces the
         *     whole detail object (no per-field merge inside it) and it must match
         *     the entry's type.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entryId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: date-time */
                        occurredAt?: string;
                        detail?: components["schemas"]["EntryDetail"];
                    };
                };
            };
            responses: {
                /** @description Updated entry. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LogEntry"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                default: components["responses"]["Problem"];
            };
        };
        trace?: never;
    };
    "/parse/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse natural language into draft entries
         * @description Stateless: text in, draft entries out — nothing is stored (ADR-0005).
         *     The app shows the confirmation card and, on Confirm, POSTs the
         *     (possibly adjusted) draft to /entries. All numeric values are
         *     estimates. Rate-limited per user per day (abuse guard). On timeout the
         *     app falls back to manual entry.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description The transcript or typed phrase, verbatim. */
                        text: string;
                        /**
                         * Format: date-time
                         * @description Device time (with offset) when the phrase was captured — anchors relative phrases like "around 4".
                         */
                        capturedAt?: string;
                    };
                };
            };
            responses: {
                /** @description Draft entries — usually one. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ParseResult"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description The text could not be interpreted as a meal, water, or workout. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
                429: components["responses"]["TooManyRequests"];
                default: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parse/photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse a photo (plate or gym whiteboard) into draft entries
         * @description Stateless like /parse/text — the image is sent to the model and
         *     discarded, never stored. A plate photo yields a meal draft; a
         *     whiteboard photo yields a workout draft.
         *
         *     Multipart confirmed by app review (pt 4). The app downscales
         *     client-side to longest edge 1568 px, JPEG quality 0.8, before upload;
         *     the 5 MB limit is a server-side backstop only.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /**
                         * Format: binary
                         * @description JPEG/PNG/WebP, max 5 MB.
                         */
                        image: string;
                        /** @description Optional user hint spoken/typed with the photo. */
                        caption?: string;
                        /** Format: date-time */
                        capturedAt?: string;
                    };
                };
            };
            responses: {
                /** @description Draft entries. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ParseResult"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Image too large. */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
                /** @description Nothing recognizable (no food, no workout) in the image. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
                429: components["responses"]["TooManyRequests"];
                default: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parse/eating-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse an eating plan (text or PDF) into a draft for confirmation
         * @description Onboarding step 3 ("eating plan"). Stateless like /parse/text: the
         *     model reads the described plan or the uploaded nutritionist PDF and
         *     returns a structured draft plus a human-readable summary the user
         *     confirms before anything is saved (ADR-0005 — nothing is persisted
         *     server-side on this call; the uploaded PDF is read and discarded). All
         *     nutrition values are estimates. Single synchronous Claude call (native
         *     PDF input, no OCR of our own) — supersedes the async import-job sketch;
         *     on timeout/failure the app falls back to manual entry. On Confirm the
         *     app POSTs the draft to the plan-create endpoint (a later ticket).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PlanImportRequest"];
                };
            };
            responses: {
                /** @description Draft eating plan. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EatingPlanDraft"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description The input could not be interpreted as an eating plan, or the `fileRef` is unknown/expired. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
                429: components["responses"]["TooManyRequests"];
                default: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parse/training-program": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse a training program (text or PDF) into a draft for confirmation
         * @description Onboarding step 4 ("training program"). Stateless like
         *     /parse/eating-plan — structured draft plus human-readable summary,
         *     confirmed before anything is saved (ADR-0005). Durations and loads are
         *     estimates or as-stated. On Confirm the app POSTs the draft to the
         *     program-create endpoint (a later ticket).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PlanImportRequest"];
                };
            };
            responses: {
                /** @description Draft training program. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TrainingProgramDraft"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description The input could not be interpreted as a training program, or the `fileRef` is unknown/expired. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
                429: components["responses"]["TooManyRequests"];
                default: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a presigned URL to upload a document
         * @description Two-phase upload for payloads that must not pass through the JSON body:
         *     API Gateway caps requests at 10 MB (OPS-011), and the parse pattern
         *     does not proxy file bytes. The app requests a short-lived presigned PUT
         *     URL, uploads the file straight to S3, then references the returned
         *     opaque `fileRef` on a parse call (e.g. /parse/eating-plan). The backend
         *     reads the object server-side for that one call and never persists it
         *     beyond the parse (ADR-0005); the bucket expires objects automatically.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description What the upload feeds. v0 only supports plan/program import.
                         * @enum {string}
                         */
                        purpose: "plan_document";
                        /**
                         * @description MIME type of the file; the PUT must send the same Content-Type.
                         * @enum {string}
                         */
                        contentType: "application/pdf";
                    };
                };
            };
            responses: {
                /** @description Presigned upload target. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Opaque handle to pass to a parse endpoint after the PUT succeeds. */
                            fileRef: string;
                            /**
                             * Format: uri
                             * @description Presigned S3 PUT URL (single use). Upload the bytes with the same Content-Type.
                             */
                            uploadUrl: string;
                            /**
                             * Format: date-time
                             * @description After this the URL and fileRef are void.
                             */
                            expiresAt: string;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                default: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the current eating plan
         * @description The newest stored version, for the Home plan row and the Eating Plan screen.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The current eating plan. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EatingPlanDraft"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                default: components["responses"]["Problem"];
            };
        };
        /**
         * Edit the current eating plan
         * @description Full-doc replace of the current version — any field is editable. The
         *     whole document is re-encrypted server-side; there is no per-field merge.
         *     Does not create a new version (past versions are frozen).
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EatingPlanDraft"];
                };
            };
            responses: {
                /** @description The edited eating plan. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EatingPlanDraft"];
                    };
                };
                400: components["responses"]["Problem"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                default: components["responses"]["Problem"];
            };
        };
        /**
         * Import (store) an eating plan as a new version
         * @description Persists a confirmed plan draft as a new version. History is capped at a
         *     server limit (default 5); importing beyond it drops the oldest version.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EatingPlanDraft"];
                };
            };
            responses: {
                /** @description Stored eating plan (the new current version). */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EatingPlanDraft"];
                    };
                };
                400: components["responses"]["Problem"];
                401: components["responses"]["Unauthorized"];
                default: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List stored eating-plan versions
         * @description The past versions (newest first), capped at the server limit. Frozen — display only.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Stored eating-plan versions. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlanVersion"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                default: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/program": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the current training program
         * @description The newest stored version, for the Home program row and the program screen.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The current training program. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TrainingProgramDraft"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                default: components["responses"]["Problem"];
            };
        };
        /**
         * Edit the current training program
         * @description Full-doc replace of the current version — any field is editable. The
         *     whole document is re-encrypted server-side; there is no per-field merge.
         *     Does not create a new version (past versions are frozen).
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TrainingProgramDraft"];
                };
            };
            responses: {
                /** @description The edited training program. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TrainingProgramDraft"];
                    };
                };
                400: components["responses"]["Problem"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                default: components["responses"]["Problem"];
            };
        };
        /**
         * Import (store) a training program as a new version
         * @description Persists a confirmed program draft as a new version. History is capped at
         *     a server limit (default 5); importing beyond it drops the oldest version.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TrainingProgramDraft"];
                };
            };
            responses: {
                /** @description Stored training program (the new current version). */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TrainingProgramDraft"];
                    };
                };
                400: components["responses"]["Problem"];
                401: components["responses"]["Unauthorized"];
                default: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/program/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List stored training-program versions
         * @description The past versions (newest first), capped at the server limit. Frozen — display only.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Stored training-program versions. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProgramVersion"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                default: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 7807 problem details. `detail` is developer-facing English; the app owns user-facing copy (ADR-0006). */
        Problem: {
            /**
             * Format: uri
             * @default about:blank
             */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
        };
        TokenPair: {
            /** @description JWT, ~15 min lifetime. */
            accessToken: string;
            /** @description Opaque, single-use (rotated on refresh), 60-day lifetime. */
            refreshToken: string;
            /** @description Access-token lifetime in seconds. */
            expiresIn: number;
        };
        /** @enum {string} */
        Units: "metric" | "imperial";
        User: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            units: components["schemas"]["Units"];
            /** Format: date-time */
            createdAt: string;
            /**
             * Format: date-time
             * @description Present only while an account deletion is pending (7-day grace).
             */
            deletionEffectiveAt?: string;
        };
        /** @description One vacation date range (BE-025). The array of these is stored server-side as a single encrypted opaque blob (per-user DEK); the server never reads or interprets it — the device drives all vacation behaviour (D1). */
        VacationRange: {
            /** Format: date */
            start: string;
            /** Format: date */
            end: string;
        };
        /**
         * @description checkin and import appear from W5/W6 onward; the app only sends the first four in v0.
         * @enum {string}
         */
        InputMethod: "voice" | "text" | "photo" | "tap" | "checkin" | "import";
        /**
         * @description Server-set. /entries creates are always `user`; health ingestion (W6, separate contract) writes the others.
         * @enum {string}
         */
        EntrySource: "user" | "apple_health" | "health_connect";
        /** @description Create payload for /entries — also exactly the draft shape returned by the parse endpoints, so a confirmed draft is POSTed as-is. */
        NewEntry: {
            /**
             * @description `checkin` (BE-024) rides this same write path as a habit check-in result; Home reads exclude it, Habits reads select it (see GET /entries `type`).
             * @enum {string}
             */
            type: "meal" | "water" | "workout" | "checkin";
            /**
             * Format: date-time
             * @description When it happened (user-adjustable), with offset.
             */
            occurredAt: string;
            inputMethod: components["schemas"]["InputMethod"];
            /** @description The user's original words, quoted on the detail screen ("logged by voice"). */
            sourcePhrase?: string;
            /**
             * @description True for AI-derived numbers — drives the "Estimated by Vita" label.
             * @default false
             */
            isEstimate: boolean;
            detail: components["schemas"]["EntryDetail"];
        };
        LogEntry: components["schemas"]["NewEntry"] & {
            /** Format: uuid */
            id: string;
            source: components["schemas"]["EntrySource"];
            /**
             * Format: date-time
             * @description Server receive time.
             */
            loggedAt: string;
            /**
             * Format: date-time
             * @description Bumped on every change — the app's offline-sync freshness marker.
             */
            updatedAt: string;
        };
        /** @description Typed payload; discriminated by the sibling `type` field on the entry. */
        EntryDetail: components["schemas"]["MealDetail"] | components["schemas"]["WaterDetail"] | components["schemas"]["WorkoutDetail"] | components["schemas"]["CheckinDetail"];
        MealDetail: {
            /** @description Short display title, e.g. "Banana & peanuts". */
            title?: string;
            items: components["schemas"]["MealItem"][];
            totals?: components["schemas"]["MacroTotals"];
        };
        MealItem: {
            name: string;
            quantity?: number;
            /** @description Free-form ("g", "ml", "handful", "slice"). Display verbatim. */
            unit?: string;
            kcal: number;
            proteinG?: number;
            carbsG?: number;
            fatG?: number;
            micros?: components["schemas"]["Micro"][];
        };
        Micro: {
            /** @description Free-form name (e.g. "Vitamin C", "Iron") — the app renders it verbatim (app review pt 7). */
            name: string;
            amount: number;
            /** @description mg, µg, g… */
            unit: string;
            /** @description Percent of the FDA Daily Value (ADR-0009). Estimate. */
            percentDaily?: number;
        };
        /** @description Denormalized totals for cards/aggregation. Server recomputes from items on write; clients treat as read-mostly. */
        MacroTotals: {
            kcal: number;
            proteinG?: number;
            carbsG?: number;
            fatG?: number;
        };
        WaterDetail: {
            /** @description Always milliliters on the wire; the app converts for imperial display. */
            amountMl: number;
        };
        WorkoutDetail: {
            title: string;
            durationMin?: number;
            /** @description Energy estimate. */
            kcal?: number;
            /** @description Closed vocabulary — exactly the 11 silhouettes the body-map UI supports (app review pt 6). Backend maps model output onto this list and drops anything unmappable ("lats"/"traps" → back, "abs"/"obliques" → core). */
            muscles?: ("chest" | "back" | "shoulders" | "biceps" | "triceps" | "forearms" | "core" | "glutes" | "quads" | "hamstrings" | "calves")[];
            exercises?: components["schemas"]["Exercise"][];
        };
        Exercise: {
            name: string;
            sets?: number;
            reps?: number;
            /** @description Always kg on the wire; the app converts for imperial display. */
            loadKg?: number;
            /** @description Same closed vocabulary as WorkoutDetail.muscles, but per exercise — drives per-exercise muscle tinting in the app (0.5.0). Optional; the backend maps model output onto this list and drops anything unmappable. The workout-level `muscles` stays for back-compat. */
            muscles?: ("chest" | "back" | "shoulders" | "biceps" | "triceps" | "forearms" | "core" | "glutes" | "quads" | "hamstrings" | "calves")[];
        };
        /** @description A single habit check-in result (BE-024). Rides the /entries write path as a `checkin` entry and is encrypted at rest like every other detail; the server stores it verbatim and never interprets it. The Idempotency-Key is deterministic — `habitId:date` — so there is one check-in per habit per day; change the answer by PATCHing the entry (same key + a different answer is a 409). No scores, no streaks. */
        CheckinDetail: {
            /** @description Device-local habit id — habit definitions live on the device (D1). */
            habitId: string;
            habitName: string;
            /** @description App-defined habit kind (e.g. plan-meal vs plain yes/no). Server-opaque. */
            kind: string;
            /** @description The user's single answer, e.g. "yes" / "not_quite". App-defined. */
            answer: string;
            note?: string;
        };
        /** @description Never persisted server-side — response only (ADR-0005). */
        ParseResult: {
            /** @description Usually one. A phrase like "had a sandwich and a big glass of water" yields two (meal + water). Capped at 5 so the app's stacked confirmation cards stay bounded (app review pt 5); the model merges or drops beyond that. */
            drafts: components["schemas"]["NewEntry"][];
        };
        /** @description Provide the plan either as free text (described/pasted) or as a reference to a PDF uploaded via POST /uploads. Exactly one of `text` or `fileRef`. */
        PlanImportRequest: {
            /** @description The plan or program described or pasted as text. */
            text?: string;
            /** @description `fileRef` from POST /uploads, pointing at an uploaded nutritionist/coach PDF. */
            fileRef?: string;
        } & (unknown | unknown);
        /** @description Never persisted server-side — response only (ADR-0005). Shaped so the confirmed draft is POSTed as-is to the plan-create endpoint (later ticket). All nutrition is estimate. */
        EatingPlanDraft: {
            /** @description Human-readable read-back shown for confirmation ("AI reads back a plan summary"). */
            summary: string;
            dailyTotals?: components["schemas"]["MacroTotals"];
            /** @description Daily micronutrient chips (estimates) for the Eating Plan screen. */
            micros?: components["schemas"]["Micro"][];
            meals: components["schemas"]["PlanMeal"][];
        };
        PlanMeal: {
            /** @description Meal slot label, e.g. "Breakfast", "Lunch", "Snack", "Dinner". */
            name: string;
            /** @description Local time-of-day (HH:MM) the plan suggests, when it states one. */
            time?: string;
            items: components["schemas"]["PlanItem"][];
        };
        PlanItem: {
            name: string;
            quantity?: number;
            /** @description Free-form ("g", "ml", "slice"). Display verbatim. */
            unit?: string;
            nutritionPerUnit?: components["schemas"]["MacroTotals"];
        };
        /** @description Never persisted server-side — response only (ADR-0005). */
        TrainingProgramDraft: {
            /** @description Human-readable read-back shown for confirmation. */
            summary: string;
            /** @description The overall split in a phrase, e.g. "Push / Pull / Legs, 5 days". */
            splitDescription?: string;
            days: components["schemas"]["ProgramDay"][];
        };
        ProgramDay: {
            /** @description Day label, e.g. "Day 1 - Push", "Upper A". */
            name: string;
            exercises: components["schemas"]["Exercise"][];
        };
        /** @description One stored eating-plan version (history). Frozen — display only. */
        PlanVersion: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            doc: components["schemas"]["EatingPlanDraft"];
        };
        /** @description One stored training-program version (history). Frozen — display only. */
        ProgramVersion: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            doc: components["schemas"]["TrainingProgramDraft"];
        };
    };
    responses: {
        /** @description Error (RFC 7807). */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Missing, expired, or invalid access token. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Resource does not exist or belongs to another user. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Rate limit exceeded. Retry after the indicated delay. */
        TooManyRequests: {
            headers: {
                /** @description Seconds to wait. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Client-generated key, unique per logical create, reused on retries. Usually a UUID; for naturally-idempotent domains it is deterministic — check-ins use `habitId:date` so a habit can be checked in once per day (BE-024). */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
